[project]
name = "reference"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cython>=3.0.12",
    "numpy>=2.2.5",
    "pycairo>=1.28.0",
    "setuptools>=80.3.1",
]
